
Zones = {}
Zones.PZ = {
    ["DutyLocation"] = {
        ["name"] = "CyberbarDutyLocation",
        ["coords"] = vector3(322.78, -927.15, 29.25),
        ["height"] = 1.8,
        ["width"] = 2.4,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 28.25,
        ["maxZ"] = 30.45,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:DUTY:TOGGLE",
        ["icon"] = "fa-solid fa-clipboard",
        ["label"] = "Toggle Duty",
        ["job"] = "cyberbar", -- < Job required to use target
    },
    ["Register"] = {
        ["name"] = "Register",
        ["coords"] = vector3(333.55, -914.11, 29.26),
        ["height"] = 0.4,
        ["width"] = 0.45,
        ["heading"] = 2,
        ["debug"] = false,
        ["minZ"] = 29.01,
        ["maxZ"] = 29.41,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:CREATE:INVOICE",
        ["icon"] = "fa-solid fa-clipboard",
        ["label"] = "Request Payment",
        ["job"] = "cyberbar", -- < Job required to use target
    },
}

Zones.PC = {
    ["crackPC"] = {
        ["name"] = "crackPC",
        ["coords"] = vector3(322.58, -928.35, 29.25),
        ["height"] = 0.6,
        ["width"] = 1.0,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.85,
        ["maxZ"] = 31.65,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:HEIST:TOGGLE:SECURITY",
        ["icon"] = "fa-solid fa-virus",
        ["label"] = "Disable Security",
    },
}

Zones.StealAble = {
    ["WeaponWallLeft1"] = { -- < This is Key
        ["name"] = "WeaponWallLeft1", -- < This is Value
        ["coords"] = vector3(338.19, -937.02, 29.25),
        ["height"] = 3.0,
        ["width"] = 1.6,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.31,
        ["maxZ"] = 30.21,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:1",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle1",
        ["value"] = "1",
    }, -- ^ This creates "k, v" or "key, value" of Zones.StealAble
    ["WeaponWallLeft2"] = {
        ["name"] = "WeaponWallLeft2",
        ["coords"] = vector3(338.24, -933.68, 29.25),
        ["height"] = 3.0,
        ["width"] = 1.2,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.35,
        ["maxZ"] = 30.2,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:2",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle2",
        ["value"] = "2",
    },
    ["WeaponWallLeft3"] = {
        ["name"] = "WeaponWallLeft3",
        ["coords"] = vector3(343.19, -933.71, 29.25),
        ["height"] = 3.0,
        ["width"] = 1.0,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.3,
        ["maxZ"] = 30.2,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:3",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle3",
        ["value"] = "3",
    },
    ["WeaponWallLeft4"] = {
        ["name"] = "WeaponWallLeft4",
        ["coords"] = vector3(343.26, -936.99, 29.25),
        ["height"] = 3.0,
        ["width"] = 1.0,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.35,
        ["maxZ"] = 30.2,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:4",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle4",
        ["value"] = "4",
    },

    ["WeaponWallBack1"] = {
        ["name"] = "WeaponWallBack1",
        ["coords"] = vector3(344.58, -901.4, 29.25),
        ["height"] = 3.0,
        ["width"] = 1.2,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 29.85,
        ["maxZ"] = 30.85,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:6",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle6",
        ["value"] = "6",
    },
    ["WeaponWallBack2"] = {
        ["name"] = "WeaponWallBack2",
        ["coords"] = vector3(337.36, -901.23, 29.25),
        ["height"] = 1.0,
        ["width"] = 3.0,
        ["heading"] = 0,
        ["debug"] = false,
        ["minZ"] = 30.1,
        ["maxZ"] = 30.9,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:GRAB:WEAPON:5",
        ["icon"] = "fa-solid fa-gun",
        ["label"] = "Take Weapon",
        ["taken"] = false,
        ["itemName"] = "sniper_rifle5",
        ["value"] = "5",
    },
}

Zones.Bar = {
    ["drinkingtap"] = {
        ["name"] = "drinkingtap",
        ["coords"] = vector3(333.43, -909.71, 29.26),
        ["height"] = 1.85,
        ["width"] = 0.55,
        ["heading"] = 359,
        ["debug"] = false,
        ["minZ"] = 28.96,
        ["maxZ"] = 30.11,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:OPENTAP",
        ["icon"] = "fa-solid fa-faucet",
        ["label"] = "Drinking Tap",
        ["job"] = "cyberbar",
    },
    ["drinkingtap2"] = {
        ["name"] = "drinkingtap2",
        ["coords"] = vector3(338.68, -911.39, 29.26),
        ["height"] = 1.8,
        ["width"] = 1,
        ["heading"] = 359,
        ["debug"] = false,
        ["minZ"] = 29.06,
        ["maxZ"] = 29.86,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:OPENTAP",
        ["icon"] = "fa-solid fa-faucet",
        ["label"] = "Drinking Tap",
        ["job"] = "cyberbar",
    },
    ["ingredientsstash"] = {
        ["name"] = "ingredientsstash",
        ["coords"] = vector3(335.89, -915.62, 29.26),
        ["height"] = 0.2,
        ["width"] = 0.5,
        ["heading"] = 359,
        ["debug"] = false,
        ["minZ"] = 28.36,
        ["maxZ"] = 28.96,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:OPEN:INGREDIENTS",
        ["icon"] = "fa-solid fa-box",
        ["label"] = "Ingredients Storage",
        ["job"] = "cyberbar",
    },
}

Zones.Stash = { -- LENT:CYBERBAR:STASH
    ["storageStash"] = {
        ["name"] = "storageStash",
        ["coords"] = vector3(338.6, -908.5, 29.26),
        ["height"] = 0.9,
        ["width"] = 1.2,
        ["heading"] = 1,
        ["debug"] = false,
        ["minZ"] = 25.61,
        ["maxZ"] = 29.01,
        ["type"] = "client",
        ["event"] = "LENT:CYBERBAR:STASH",
        ["icon"] = "fa-solid fa-box",
        ["label"] = "Product Storage",

        ["stashname"] = "Cyberbar Storage",

        ["jobrequired"] = true,
        ["requirecid"] = false,
        ["gangrequired"] = false,

        ["gang"] = "",
        ["job"] = "cyberbar",
        ["cid"] = {""},
        ["stashSize"] = 1250000,
        ["stashSlots"] = 50,
    },
}